schema_version = "1.0.0"
id = "rmKit_uv"
version = "1.0.3"
name = "rmKitUV"
tagline = "Collection of Tools"
maintainer = "Timothee Yeramian <lead.acrysoft@gmail.com>"
type = "add-on"

license = [
  "SPDX:GPL-3.0-or-later",
]

website = "https://rmkit.readthedocs.io/en/latest/"
tags = ["Mesh", "UV", "Material"]

blender_version_min = "4.2.0"

wheels = [
  "./wheels/rmlib-0.1.0-py3-none-any.whl"
]

[permissions]
files = "read/write hotspots to disk"


[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".git",
  ".*",
  "*.zip",
  "*.bat",
  "*.hot",
  "*.md",
]